### ISSUE TITLE
Peak detection/fitting and deconvolution

### ISSUE THREAD

**Issue by annliirosales** [jamesETsmith/msanalysis#3]
- **Peak detection/fitting** would help speed up QMS data analysis immensely. This would include generating isotope patterns based on possible etch products. Then, fitting would entail fitting the calculated patterns to the experimental data. Fitting output would include quality of fitting (eg, percent match to the isotope fingerprints). 

- **Peak deconvolution** would help identify species with overlapping m/z values. Deconvolution would involve linear combination of relative peak intensities from different species.

**Comment by jamesETsmith** [comment]
Hey @annliirosales, I think this is done. I just add the changes so try em out and let me know what you think. If you're happy just close this issue.

**Comment by annliirosales** [comment]
Hi @jamesETsmith , thanks for adding the features! I just encountered a potential problem in ex06 and ex09. I wanted to obtain a calculated pattern for Sn2(CH3)5 (input as Sn2C5H15). The output pattern seems to be missing a peak at 319, which is about 21% according to an isotope calculator that I use on the side (https://www.sisweb.com/mstools/isotope.htm). I've attached the output plots from ex06 and ex09 for your reference. Thanks!
![ex6](https://user-images.githubusercontent.com/56844738/75817424-48e7ac80-5d54-11ea-9e91-103d97af1d66.png)
![ex9](https://user-images.githubusercontent.com/56844738/75817425-49804300-5d54-11ea-80a3-dc2a7c011176.png)

**Comment by annliirosales** [comment]
Also, ex06 and ex09 don't seem to work for formula containing Indium. I tried InCl, InCl2 and In(CH3)2 and received the following error message: "Determination of memory status is not supported on this platform, measuring for memoryleaks will never fail
python(17091,0x1189515c0) malloc: *** error for object 0x7fecca920bb8: pointer being freed was not allocated
python(17091,0x1189515c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6"
Any idea of what's going on with Indium? Thanks!

**Comment by jamesETsmith** [comment]
Hi @annliirosales, the first problem is fixed with the commit I added earlier this morning. The second problem is a bit more complicated since it's coming from one of the dependencies, `pyOpenMS`. I've [contacted](https://github.com/OpenMS/OpenMS/issues/4563) the developers of that package and hopefully we can figure out a solution soon.

**Comment by jamesETsmith** [comment]
I just added another commit with a patch that will allow you to work with Indium while we wait for a response from pyopenms. See [here](https://github.com/jamesETsmith/msanalysis#patches) for details about applying the patch.

**Comment by jamesETsmith** [comment]
Hi @annliirosales I'm going to close this issue. If there is still work to be done feel free to reopen it.
