### ISSUE TITLE
ex6: missing isotope for Ge

### ISSUE THREAD

**Issue by annliirosales** [jamesETsmith/msanalysis#8]
ex6_iso_abundancy is missing an isotopic abundance for Germanium (Ge). According to this website (https://www.sisweb.com/mstools/isotope.htm), Ge has an abundance at 76 amu. However, ex6 does not display 76 amu (the plot stops at 74 amu; please see attached). Not sure if the data base needs to updated.
![ex6](https://user-images.githubusercontent.com/56844738/106683618-1658bc00-6582-11eb-9c3f-c2480fd5a4db.png)
<img width="779" alt="Ge isotopes" src="https://user-images.githubusercontent.com/56844738/106683639-21abe780-6582-11eb-8eb7-3a3e6b646c70.png">

**Comment by jamesETsmith** [comment]
Thanks for the heads up @annliirosales. It looks like this problem is stemming from a dependency (openms).  I just opened an issue with them OpenMS/OpenMS/issues/5152. I'll add update the patch we use so msanalysis will work while they fix the bug.

**Comment by jamesETsmith** [comment]
b50008a should fix this. Feel free to close the issue if everything is working for you now.

**Comment by jamesETsmith** [comment]
Hi @annliirosales, moving the conversation from the to commit to this issue to keep it in one place. You shouldn't need to modify any files. From anywhere in msanalysis, you can run `git pull` to get the updated files, then in the `patches directory` you can run `python add_elements.py` as described [here](https://github.com/jamesETsmith/msanalysis#patches). When you run `python add_elements.py` make sure that the correct Python environment is active.

**Comment by annliirosales** [comment]
Got it. It's working now! Thanks @jamesETsmith!
